name = "DbWrapper"
uuid = "2979e83e-5944-47e2-8c9e-b67802577852"
version = "0.1.0"
authors = ["Deniz Frick <31888274+deniz-frick@users.noreply.github.com>"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LibPQ = "194296ae-ab2e-5f79-8cd4-7183a0a5a0d1"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"

[compat]
DataFrames = "1.8.1"
JSON3 = "1.14.3"
LibPQ = "1.18.0"
Oxygen = "1.10.0"
